steps:
  # PASSO 1: Transforma seu código em uma imagem (O que você já faz)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/tarefa-flask', '.']

  # PASSO 2: Pega essa imagem e joga no Cloud Run (O que está faltando!)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'tarefa-flask'  # <-- Verifique se esse é o nome no seu Cloud Run
      - '--image'
      - 'gcr.io/$PROJECT_ID/tarefa-flask'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/$PROJECT_ID/tarefa-flask'