name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Build and push Docker image
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/tarefas-flask

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy tarefa-flask \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/tarefas-flask \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated
    - name: Test project id
      run: echo "Projeto: ${{ secrets.GCP_PROJECT_ID }}"
